- name: Creates directory
  file:
    path: ~/backend
    state: directory

- name: Extract backend
  become_user: ubuntu
  unarchive:
    src: /home/backend.tar.gz
    dest: ~/backend

- name: Install dependencies
  shell: |
    sudo apt-get update -y
    sudo apt-get install npm

- name: Execute node app
  shell: |
    sudo pm2 stop default
    sudo pm2 start npm -- start
  register: execute_node

- name:  start app
  command:  pm2 start main.js
  args:
    chdir: ~/backend/dist