- name: Creates directory
  file:
    path: ~/backend
    state: directory

- name: Extract backend
  become_user: ubuntu
  unarchive:
    src: /home/backend.tar.gz
    dest: ~/backend

- name: Install dependencies
  become: true
  shell: |
    cd ~/backend
    sudo npm install

- name: Build and run PM2 server
  shell: |
    cd ~/backend
    sudo npm run build
    pm2 stop default
    pm2 start npm -- start
